name: D

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  b:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install flask requests pyinstaller
      - run: pyinstaller --onefile --name SporTahmin --add-data "templates;templates" --add-data "veri;veri" app.py
      - uses: actions/upload-artifact@v4
        with:
          name: SporTahmin
          path: dist/SporTahmin.exe
